# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tech Thoughts and Stuff
email: techthoughtsandstuff@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Blog about stuff I find interesting in technology, particularly cybersecurity. Different papers, projects and other
endeavors from myself and others. Thanks for the interest!  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: BlakeMoss11
github_username:  bmoss6

# Build settings
markdown: kramdown
